package org.springside.examples.user.dao;

import org.springside.examples.user.model.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_user
     *
     * @mbggenerated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_user
     *
     * @mbggenerated
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_user
     *
     * @mbggenerated
     */
    User selectByPrimaryKey(Long id);
    
    User selectBySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(User record);
}